"use strict";
// Obsidian loads main.js without Node's normal relative-module resolution.
// Bundle the small local core into one CommonJS entry, without extra dependencies.
const fs = require("node:fs");
const path = require("node:path");
const source = fs.readFileSync(path.join(__dirname, "plugin.js"), "utf8");
const core = fs.readFileSync(path.join(__dirname, "core.js"), "utf8");
if (!source.includes('require("./core")')) throw new Error("Core import missing");
const bundled = source.replace('require("./core")', () => `(function () {\nconst module = { exports: {} };\n${core}\nreturn module.exports;\n})()`);
fs.writeFileSync(path.join(__dirname, "main.js"), "// Generated by build.cjs; edit plugin.js and core.js.\n" + bundled);
fs.copyFileSync(path.join(__dirname, 'ui.css'),path.join(__dirname,'styles.css'));
console.log("Built attention-allocator/main.js");
